library(MASS)
library(purrr)
library(dplyr)
library(glue)
library(tidyverse)
library(nlshrink)
library(stargazer)
library(plotly)
library(ggthemes)
library(latex2exp)
library(patchwork)
library(cowplot)
library(mvtnorm)
library(future.apply)
library(progressr)
handlers(global = TRUE)
handlers("txtprogressbar")
cl <- parallel::makeCluster(20)
plan(cluster, workers = cl)
